# Generated by Django 5.0.6 on 2024-07-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytvideos',
            name='views',
            field=models.CharField(max_length=10),
        ),
    ]
